using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Helpers;
using System.Text.RegularExpressions;
using Microsoft.WindowsAzure.Mobile.Service;
using Microsoft.WindowsAzure.Mobile.Service.Security;
using alltheairgeadmobileService.Models;
using alltheairgeadmobileService.DataObjects;
using EmailValidation;

namespace alltheairgeadmobileService.Controllers
{
    [AuthorizeLevel(AuthorizationLevel.Anonymous)]
    public class CustomRegistrationController : ApiController
    {
        public ApiServices Services { get; set; }

        // POST api/CustomRegistration
        public HttpResponseMessage Post(RegistrationRequest Request)
        {
            if (!EmailValidator.Validate(Request.Email, true))
            {
                return this.Request.CreateResponse(HttpStatusCode.BadRequest, "Invalid email format");
            }
            else if (Request.Password.Length < 8)
            {
                return this.Request.CreateResponse(HttpStatusCode.BadRequest, "Invalid password (at least 8 chars required)");
            }

            // Use local database context for testing local to service
            //alltheairgeadmobileContext context = new alltheairgeadmobileContext();
            alltheairgeadContext context = new alltheairgeadContext(Services.Settings["ExistingDbConnectionString"]);
            UserProfile account = context.UserProfiles.Where(a => a.Email == Request.Email).SingleOrDefault();
            if (account != null)
            {
                return this.Request.CreateResponse(HttpStatusCode.BadRequest, "Email already exists");
            }
            else
            {
                UserProfile newAccount = new UserProfile
                {
                    Email = Request.Email,
                    //HashedPassword = CustomLoginProviderUtils.hash(Request.Password)
                };
                context.UserProfiles.Add(newAccount);
                context.SaveChanges();

                // Get autogenerated UserId to use.
                newAccount = context.UserProfiles.Where(a => a.Email == Request.Email).SingleOrDefault();
                webpages_Membership newMembership = new webpages_Membership
                {
                    UserId = newAccount.UserId,
                    CreateDate = DateTime.Now,
                    IsConfirmed = true,
                    LastPasswordFailureDate = null,
                    PasswordFailuresSinceLastSuccess = 0,
                    Password = Crypto.HashPassword(Request.Password),
                    PasswordChangedDate = null,
                    PasswordSalt = "blank",
                    PasswordVerificationToken = null,
                    PasswordVerificationTokenExpirationDate = null
                };
                context.Memberships.Add(newMembership);
                context.SaveChanges();

                return this.Request.CreateResponse(HttpStatusCode.Created);
            }
        }

        public HttpResponseMessage Post(string Email, string Password)
        {
            RegistrationRequest Request = new RegistrationRequest();
            Request.Email = Email;
            Request.Password = Password;

            var result = Post(Request);
            return result;
        }
    }
}
